name: Build and Release App

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: macos-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 赋予执行权限并运行构建脚本
      - name: Run build script
        run: |
          chmod +x ./build.sh
          ./build.sh

      # 创建 Release 并上传文件
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src/build/ladderup-4.1.10-arm64.dmg
            src/build/ladderup-4.1.10.dmg
            src/build/ladderup Setup 4.1.10.exe
          body: |
            This release includes the following builds:
            - macOS (Intel/ARM64)
            - Windows x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
