name: Build macOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install electron --save-dev

      - name: Build macOS app
        run: target=darwin npx electron-builder build --macos --arm64
